[package]
name = "test_libloading"
version = "0.1.0"
authors = ["Byeonggon Lee <gonny952@gmail.com>"]

[dependencies]
libloading = "^0.5"

[dev-dependencies.dltest]
path = "dltest"
version = "^0.1.0"
